### ISSUE TITLE
The ability to do "Unlink"

### ISSUE THREAD

**Issue by make-your-soft-better** [Teascade/pipeswitch#15]
There is an idea to add the ability not only to make new connections, but also to disconnect existing ones.
Example:
```
[link.FLStudioMySuperProfessionalAudioCard]
source = ".*mySuperDuperSoundCard*"
sink = ".*FL64.*"

There is not "link" but "unlink"
[unlink.FLStudioMyFreakyNoisyMotherboardCard]
source = ".*alsa_input.pci-0000_00_1b.0.analog-stereo*"
sink = ".*FL64.*"
```
That would be just great.

If there are already some ways to do this, please write.

**Comment by Teascade** [comment]
Hi! Thanks for participating!

While this idea is very interesting on the surface, I fear it doesn't align with the design-philosophy of pipeswitch, at least.

To elaborate: Pipewire itself already has a concept of [per-client permissions](https://docs.pipewire.org/page_access.html). While pipeswitch doesn't really use this (I have no idea what permissions it uses currently, probably unrestricted manager-permissions), that is a problem within the implementation rather than design.

Pipeswitch as inspired by this, was made with the design-philosophy that it would only need permissions to create links, and to modify the links made by pipeswitch in the past. Destroying links made by other clients would go against this philosophy.

If you like, you can make a custom fork such a feature, but I have no intention of including such features into pipswitch until further notice.

Again, thanks for noticing pipeswitch in any case!
